name: parquet-hs
version: 0.1.0.0
synopsis: Streaming Parquet reader
description: Please see the README on GitHub at <https://github.com/yigitozkavci/parquet-hs#readme>
author: Yigit Ozkavci
copyright: 2019-2021 Yigit Ozkavci
maintainer: Yigit Ozkavci <yigitozkavci8@gmail.com>
category: Compression
license: BSD3

ghc-options: -Wall -O2 -fspecialise-aggressively

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - ViewPatterns

extra-source-files:
  - ChangeLog.md
  - README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - pinch
  - text
  - bytestring
  - binary
  - mtl
  - containers
  - conduit
  - binary-conduit
  - monad-logger
  - conduit-extra
  - generic-lens
  - microlens-platform
  - safe
  - aeson
  - unordered-containers
  - lifted-async
  - serialise
  - http-conduit
  - http-client
  - http-types
  - vector
  - pretty-simple
  - relude

tests:
  parquet-hs-unit:
    main: Spec.hs
    source-dirs: tests/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - parquet-hs
    - hspec
    - QuickCheck
    - bytestring
    - binary
  parquet-hs-integration:
    main: Spec.hs
    source-dirs: tests/integration
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - parquet-hs
    - hspec
    - QuickCheck
    - bytestring
    - mtl
    - binary
    - filepath
    - process
    - aeson
    - text
    - conduit
    - monad-logger
    - pretty-simple
